---
- name: Ansible_CF project
  hosts: tag_Name_Slavehost
  become: true
  
  vars:
    # Specify the path to your .env file on your local machine
    backend_env_file: /home/ubuntu/env/backend/.env
    frontend_env_file: /home/ubuntu/env/frontend/.env
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - mongodb-server
          - nodejs
          - npm
          - git
        state: present

    - name: Start MongoDB service
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Clone MERN app from GitHub repository
      git:
        repo: "https://github.com/chyke007/Yum-food"
        dest:  /home/ubuntu/yum-food/
        clone: yes

    - name: Copy server .env file to the server
      copy:
        src: "{{ backend_env_file }}"
        dest: /home/ubuntu/yum-food/.env
        mode: 0644

    - name: Copy Frontend .env file to the frontend folder
      copy:
        src: "{{ frontend_env_file }}"
        dest: /home/ubuntu/yum-food/frontend/.env
        mode: 0644

    - name: Install Packages
      command: npm install 
      args:
        chdir: /home/ubuntu/yum-food/

    - name: Run seeder function
      command: npm run heroku-postbuild 
      args:
        chdir: /home/ubuntu/yum-food/

    - name: Open port 4000 for Node.js app
      ufw:
        rule: allow
        port: 4000
        proto: tcp

    - name: Start Node.js app
      command: npm start
      args:
        chdir: /home/ubuntu/yum-food/